# Generated by Django 5.1 on 2024-09-29 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.planner')),
            ],
        ),
    ]
