# Generated by Django 5.1 on 2024-09-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='planner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='planner.planner'),
        ),
    ]
