# Generated by Django 5.1 on 2024-08-26 22:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField(default=1)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
