# Generated by Django 5.1 on 2024-09-29 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ALUGUEL', 'Aluguel'), ('DIVIDENDOS', 'Dividendos'), ('RENDA_EXTRA', 'Renda extra'), ('RENDIMENTOS', 'Rendimentos'), ('OUTROS', 'Outros')], max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_earning', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
