# Generated by Django 5.1 on 2024-09-29 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('AUTOMOVEL', 'Automóvel'), ('DESPESAS_MENSAIS', 'Despesas mensais'), ('SALARIO', 'Salário'), ('VIAGEM', 'Viagem'), ('OUTROS', 'Outros')], max_length=50)),
                ('spending_target', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
